---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos7
    driver:
      box: bento/centos-7.2

suites:
  - name: server
  - name: client1
  - name: client2
  - name: web1
  - name: web2